from sekv.backbone import FrozenBackbone, MODEL_REGISTRY, ModelSpec, PrefillOutputs, build_backbone
from sekv.arch import ArchAdapter, LlamaArchAdapter, MistralArchAdapter, Qwen2ArchAdapter, build_arch_adapter
from sekv.config import (
    EvalConfig,
    LossConfig,
    MemoryConfig,
    ModelConfig,
    PathsConfig,
    RoutingConfig,
    SeKVConfig,
    SegmentationConfig,
    TrainConfig,
    load_config,
    load_eval_config,
)
from sekv.attention import (
    GroupEntries,
    assemble_group_entries,
    budget_select,
    build_log_gate,
    decode_step_layer,
    masked_softmax_attention,
    ste_zoom_gate,
)
from sekv.data import RedPajamaLongDocuments, build_dataloader, curriculum_schedule
from sekv.generate import GenerationConfig, SVDPrefetcher, generate, generate_text, load_sekv_checkpoint, sekv_forward_token
from sekv.losses import budget_loss, distill_loss, recon_loss, total_loss, zoom_loss
from sekv.memory import (
    LayerMemory,
    SpanEntry,
    SpanFactors,
    SpanMemory,
    build_layer_memory,
    build_span_memory,
    effective_rank,
    reconstruct_span,
    span_weights,
)
from sekv.modules import RankGatePredictor, SeKVModules
from sekv.segmentation import SegmentationResult, Span, compute_surprisal, segment_prefill, segment_sequence
from sekv.teacher import TeacherSignals, aggregate_span_mass, build_teacher_signals, coverage_targets, extract_teacher_attention, mine_query_positions
from sekv.train import budget_anneal, build_optimizer, build_scheduler, train, train_step

__all__ = [
    "FrozenBackbone",
    "MODEL_REGISTRY",
    "ModelSpec",
    "PrefillOutputs",
    "build_backbone",
    "ArchAdapter",
    "build_arch_adapter",
    "LlamaArchAdapter",
    "MistralArchAdapter",
    "Qwen2ArchAdapter",
    "LossConfig",
    "EvalConfig",
    "MemoryConfig",
    "ModelConfig",
    "PathsConfig",
    "RoutingConfig",
    "SeKVConfig",
    "SegmentationConfig",
    "TrainConfig",
    "load_config",
    "load_eval_config",
    "GroupEntries",
    "ste_zoom_gate",
    "masked_softmax_attention",
    "assemble_group_entries",
    "build_log_gate",
    "budget_select",
    "decode_step_layer",
    "RedPajamaLongDocuments",
    "build_dataloader",
    "curriculum_schedule",
    "GenerationConfig",
    "SVDPrefetcher",
    "load_sekv_checkpoint",
    "sekv_forward_token",
    "generate",
    "generate_text",
    "TeacherSignals",
    "extract_teacher_attention",
    "aggregate_span_mass",
    "coverage_targets",
    "mine_query_positions",
    "build_teacher_signals",
    "distill_loss",
    "zoom_loss",
    "recon_loss",
    "budget_loss",
    "total_loss",
    "build_optimizer",
    "build_scheduler",
    "budget_anneal",
    "train_step",
    "train",
    "Span",
    "SegmentationResult",
    "compute_surprisal",
    "segment_sequence",
    "segment_prefill",
    "RankGatePredictor",
    "SeKVModules",
    "SpanFactors",
    "SpanEntry",
    "LayerMemory",
    "SpanMemory",
    "span_weights",
    "build_layer_memory",
    "build_span_memory",
    "reconstruct_span",
    "effective_rank",
]
